#!/bin/bash
# Grab the latest Atom revision and build it. A Makefile (or grunt or similar)
# is probably a better way to go about this, but the script works.
TMPDIR=/tmp

cd ~/src/atom

# checkout specific branch
# else use master
## note: this is the command recommended by https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md
# git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
if [ "$#" -eq 1 ]
then
  git checkout -b $1
else
  echo git checkout master
fi

git pull

# First time I ran this, it didn't finish the build, may need to execute
# multiple times.
script/build


# clean up any previous .deb files.
#rm $TMPDIR/atom-build/*.deb

# build the deb
script/grunt mkdeb

# last package is the one we want
# TODO: find a better way for supporting specific branches.
PKGNAME=`ls $TMPDIR/atom-build/*.deb | tail -n 1`
sudo dpkg -i $PKGNAME
