#!/bin/bash
# atom-packages to be installed. can be run as user to install only for that
# user, or root if to be installed system wide

PACKAGES=
"
build
git-plus
language-gcode
language-gitignore
language-latex
minimap
pdf-view
seti-syntax
seti-ui
"

apm install ${PACKAGES[@]}
