#!/bin/bash
# To users: this script needs to be run as root or with sudo

# Add repositories here
REPOS="
ppa:apt-fast/stable
ppa:boost-latest/ppa
ppa:octave/stable
ppa:git-core/ppa
"

BAD_PACKAGES="
libboost1.55
"

# Add packages here
PACKAGES="
google-chrome-stable
openssh-server
octave
git
build-essential
libreoffice
texlive-full
mysql-client
iojs
build-essential
libgnome-keyring-dev
fakeroot
vlc
cifs-utils
gparted
unetbootin
transmission
"
# Other repos
# iojs
curl -sL https://deb.nodesource.com/setup_iojs_1.x | sudo bash -

#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# Adobe Source Code Pro Font
# A nice monotype font from Adobe (and it's open source)
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
mkdir -p /usr/share/fonts/opentype
git clone https://github.com/adobe-fonts/source-code-pro.git /usr/share/fonts/opentype/source-code-pro
fc-cache -f -v

#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# No need to go below this line unless debugging.
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

# add all repositories
for r in $REPOS
do
  apt-add-repository -y $r
done

# update package lists
apt-get update

# install apt-fast
apt-get install -y apt-fast

# install all packages as a single apt-fast command
apt-fast install ${PACKAGES[@]}
